<?php

/**
 * Implements hook_form_alter().
 */
function label_tag_form_alter(&$form, &$form_state, $form_id) {
  // Our target is the display form of the field_ui module
  if($form_id != 'field_ui_display_overview_form') return;

  $new_options = array(
    'h2' => t('Heading 2'),
    'h3' => t('Heading 3'),
    'h4' => t('Heading 4'),
    'h5' => t('Heading 5'),
    'h6' => t('Heading 6'),
  );

  foreach($form['fields'] as $key => $field) {
    // Ignore fields with no label or options
    if(!isset($field['label']['#options'])) continue;

    // Add the new options to the current ones
    $form['fields'][$key]['label']['#options'] = $field['label']['#options']
                                               + $new_options;
  }
}

/**
 * Implements hook_theme().
 */
function label_tag_theme($existing, $type, $theme, $path) {
  return drupal_find_theme_templates($existing, '.tpl.php', $path);
}
